language: java
branches:
- develop
- "/^release-[0-999].[0-999]$/"
- master
notifications:
  email:
    recipients:
    - nelsonlz@outlook.com
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nelson-lpz-soft
  -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU2
  on:
    branch: master
  app: api-rest-basika
